version: '3'

services:

  java:
    build: .
    image: javadev
    container_name: javadev
    restart: always
    working_dir: /opt/app
    tty: true
    volumes:
      - ../:/opt/app
      - ./.vscode-server:/root/.vscode-server
    ports:
      - 2222:22